name: sesuaiformat-script
services:
  sesuaiformat-script:
    container_name: sesuaiformat-script
    build: .
    image: sesuaiformat-script:1.0.0
    cpus: 0.2
    mem_limit: 256m
    mem_reservation: 128m
    env_file:
     - .env
    restart: unless-stopped
    networks:
     - pepet-network

networks:
  pepet-network:
    external: true
